"use client"
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import {Inter,Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { useEffect, useState } from "react";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Outfit({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [userLocation,setUserLocation]=useState();

    useEffect(()=>{
      getUserLocation();
    },[])
    const getUserLocation=()=>{
      navigator.geolocation.getCurrentPosition(function(pos){
        console.log(pos)
      })
    }
  
  
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${outfit.variable} ${outfit.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
